### ISSUE TITLE
Issue: Only 1 dimension allowed in contentTypes

### ISSUE THREAD

**Issue by kristofzerbe** [estruyf/vscode-front-matter#197]
**Describe the bug**
In case a Frontmatter subentry has to be taken as name of a custom contentType, it won't work. For example:

**FrontMatter**

```
---
title: xxx
subtitle: yyy
photo:
  file: my-photo.jpg
  name: My Photo
---
```
**Setting**
```
"frontMatter.taxonomy.contentTypes": [
	"name": "default",
    "previewPath": "/static/photos/",
	"fields": [
		...
        {
          "title": "Article preview",
          "name": "photo.file",
          "type": "image"
        }
	]
]
```
**Expected behavior**
Subentries should be noted if they are separated by a period.
