### ISSUE TITLE
Enhancement: Keep comment

### ISSUE THREAD

**Issue by mjy9088** [estruyf/vscode-front-matter#242]
**Is your feature request related to a problem? Please describe.**
I **put comments** for readability in the front matter. modified by this extension, _**all comments gone!**_ :tada:

**Describe the solution you'd like**
use [yaml](https://www.npmjs.com/package/yaml) or similar package to [keep comments](https://eemeli.org/yaml/v1/#comments)

**Comment by estruyf** [comment]
Thanks @mjy9088 this is indeed a known issue. Unfortunatly, this is related to the YAML parser. The sample you provided is still going to give the same issue. The YAML parser will keep only the comments that were added before the front matter section.

![Screenshot 2022-02-08 at 09 54 39](https://user-images.githubusercontent.com/2900833/152952018-3c1d858e-b7be-4a5c-a6b7-37b112099f4e.png)

I have just tested this by writing a parser based on the sample you gave me. My front matter looks as follows:

![Screenshot 2022-02-08 at 09 56 44](https://user-images.githubusercontent.com/2900833/152954742-7b8a0bdb-3ab6-410f-a3ee-7228320f2fb7.png)

The parser returns:

![Screenshot 2022-02-08 at 09 56 44](https://user-images.githubusercontent.com/2900833/152954796-c3fac24f-a8ff-4786-a12d-c9c9556003ca.png)

> **Important**: Notice the `comment` and `commentBefore`, both are `null`.

Went a bet further, and checked what it parsed, and unfortunately, it also removes the comments:

![Screenshot 2022-02-08 at 10 10 24](https://user-images.githubusercontent.com/2900833/152955014-7589fa16-6e6f-4aff-97d9-852c807cf9b2.png)

> **Info**: This is the data map from all the front matter fields it parsed. I'm using 13. and get 13 back, but the three comments are just ignored.

If you know a way to handle this, feel free to suggest or contribute. I'm sure this issue can help others as well.

**Comment by mjy9088** [comment]
https://codesandbox.io/s/yaml-comment-test-jl08o

```javascript
import YAML from "yaml";

import "./styles.css";

const original = `
# This is YAML
---
title: YAML Test
slug: yaml-test
date: '2022-02-08T17:34:18.844Z'
lastmod: '2022-02-09T10:08:20.682Z'
tags:
  - 'lang:XML'
  # TODO: add more languages
  # this comment is ok also
  - Test
`;

const parsed = YAML.parseDocument(original);

const serialized = parsed.toString();

document.getElementById("app").innerText = serialized;
```

The parser looks fine.

Since I had previously used the [comment-json](https://www.npmjs.com/package/comment-json) module (almost same to using global `JSON` object), I expected that using the yaml module would also be straightforward.

...but now that I see it, using this module is not that simple 😢 it seems like a lot of changes are needed to use this module.

**Comment by estruyf** [comment]
This works, as you just parse it and go straight to a `string` again. The reason why it doesn't work that easy is that the front matter will get parsed to `JSON`, because of that the comments are removed.

Internally we use the `parse` method, and that does `parsed.toJSON()` on the parsed document and so it loses the comments.

**Comment by mjy9088** [comment]
how about using `yawn-yaml` module to serialize?

```javascript
const fs = require("fs");
const YAWN = require("yawn-yaml/cjs");
const yaml = require("js-yaml");

const originalText = fs.readFileSync("./original.yml").toString();
const yawn = new YAWN(originalText);
const content = yaml.load(originalText);

const test = "[TEST] THIS CONTENT IS DYNAMICALLY ADDED! - "
const changedContent = {
  ...content,
  tags: [
    test + "add",
    ...content.tags.map((a, i) => i ? [test + "more", a] : a).flat(1),
    test + "tags"
  ]
};

yawn.json = changedContent;

console.log(yawn.yaml);
```

input:

```yaml
# This is YAML
---
title: YAML Test
slug: yaml-test
date: '2022-02-08T17:34:18.844Z'
lastmod: '2022-02-09T10:08:20.682Z'
tags:
  - 'lang:XML'
  # TODO: Check this comment remains
  - Test
```

output:
```yaml
# This is YAML
---
title: YAML Test
slug: yaml-test
date: '2022-02-08T17:34:18.844Z'
lastmod: '2022-02-09T10:08:20.682Z'
tags:
  - '[TEST] THIS CONTENT IS DYNAMICALLY ADDED! - add'
  # TODO: Check this comment remains
  - 'lang:XML'
  - '[TEST] THIS CONTENT IS DYNAMICALLY ADDED! - more'
  - Test
  - '[TEST] THIS CONTENT IS DYNAMICALLY ADDED! - tags'
 ```
