### ISSUE TITLE
Automagically populate featuredImage, featuredImagePreview and images

### ISSUE THREAD

**Issue by f-bader** [estruyf/vscode-front-matter#30]
It would be great if there would be a feature to populate the follwing based on the images in the current post.

```yaml
featuredImage: "images/myPostImage.png"
featuredImagePreview: "images/myPostImage.png"
images:
 - "/<slug>/images/myPostImage.png"
```

The `images` attribute should represent the full path to the image including slug. Otherwise the OG and Twitter cards do not work properly.
