### ISSUE TITLE
Enhancement: Better support for using block fields in block fields

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#366]
Currently, it is not possible to create the following structure:

```
ingredients:
  - wet:
    - water:
    	quantity: 1
    	unit: cup
  - dry:
    - flour:
    	quantity: 10
    	unit: oz
```
