### ISSUE TITLE
Creating articles from template does not apply settings

### ISSUE THREAD

**Issue by c-antin** [estruyf/vscode-front-matter#38]
Those are my settings:
```json
{
    "frontMatter.taxonomy.noPropertyValueQuotes": [
        "date",
        "lastmod"
    ],
    "frontMatter.taxonomy.dateFormat": "yyyy-MM-dd'T'HH:mm:ssxxx"
}
```

This is the template:
```yaml
---
date: 2021-01-01T00:00:00+00:00
lastmod: 2021-01-01T00:00:00+00:00
title: empty
---
```

This is the created article:
```yaml
---
date: '2021-06-27T01:51:06+02:00'
lastmod: 2021-01-01T00:00:00.000Z
title: Test
---
```

`date` is quoted and `lastmod` changed date format. But should be updated, I guess.

May be related to #34 

But overall: nice extension :)
