### ISSUE TITLE
Enhancement: Parameter support for defining paths

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#425]
Feedback from Twitter: https://twitter.com/LoreZyra/status/1574625380580802560

> Better docs on how to build FrontMatter templates would be good. Parameter to define custom path similar to Hexo (eg. /:lang/:category/:title/)…

## Enhancements

- Support parameters in preview paths. This functionality will allow the user to use front matter data to generate the preview URL.
- Parameter support for content folder paths.
  - *Waiting for more feedback!*

**Comment by estruyf** [comment]
Thanks @lorezyra for your feedback.

> How do I change the FrontMatter dashboard to show my img: parameter from the MD frontmatter? There's no way to customize the the preview cards?

You can do this by setting the `isPreviewImage` property to `true` for your content type like documented here: https://frontmatter.codes/docs/content-creation/fields#image

**Comment by lorezyra** [comment]
Also, I have a folder structure for my categories. I might have a post 3 folders (categories) deep. Those categories are a part of the path. For example: `/Science/Health/weight-loss.html` or `/Work/Programming/JS/ExtJS/Sencha.html`

**Comment by lorezyra** [comment]
Is this what I should be looking for?
https://frontmatter.codes/docs/content-creation/placeholders

**Comment by estruyf** [comment]
@lorezyra, these placeholders are used when you are creating content. In your case, you want to let Front Matter know how it needs to show your page in the preview. This can only be done with the `previewPath` properties and they don't have the ability yet to use your page its front matter to generate the preview URL.

BTW: how is your article's front matter structured? When you say: "3 folders (categories) deep", how do you set it in the page?

**Comment by lorezyra** [comment]
Here's a sample of my front-matter:

```yml
---
title: 20 powerful visuals about psychology & Life
tags:
  - Psychology
categories:
  - Life_生活
sticky: 999
comments: true
lang: en
type: HEXO/post
toc: true
tocOpen: true
indexing: true
display_tag_onHome: true
recommendedSection: false
donate: true
geolocation: Chiba, Japan
mathjax: false
share: false
copyright: true
copyLicense: false
copyLicenseURL: false
copyLicenseDesc: false
sourceUrl: false
sourceAuthor: false
sourceAuthorImg: false
sourcePublishDate: false
img: /2022/0926/Life_生活/20-powerful-visuals-about-psychology-life/AdobeStock_267678616_Maslows-needs-pyramid.svg
openGraph_img: /2022/0926/Life_生活/20-powerful-visuals-about-psychology-life/AdobeStock_267678616_Maslows-needs-pyramid.png
readTime: false
wordCount: false
date: 2022-09-26 21:55:14
updated: 2022-09-26 21:55:14
excerpt: Deconstruct complex ideas and long-form articles into simple, and thought-provoking visuals.
---
```

---

Categories are automatically generated from my folder's tree structure.

For example, the post `/Work/Programming/JS/ExtJS/Sencha.html` would have the following value for `categories`:
```yml
categories:
  - Work
  - Programming
  - JS
  - ExtJS
```
