### ISSUE TITLE
Enhancement: Add support HEXO's post asset folders 

### ISSUE THREAD

**Issue by estruyf** [estruyf/vscode-front-matter#430]
This is a HEXO feature. https://hexo.io/docs/asset-folders defines it better. I have the `_config.yml` parameter `post_asset_folder: true` set.

```yml
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
```

_Originally posted by @lorezyra in https://github.com/estruyf/vscode-front-matter/issues/428#issuecomment-1264311609_
