### ISSUE TITLE
Tags are not displayed by "Front Matter: Insert tags" if a null tag is included in "frontMatter.taxonomy.tags"

### ISSUE THREAD

**Issue by m5ls7h** [estruyf/vscode-front-matter#7]
My blog includes some blog posts with null tags in the front matter:
```yaml
---
title: test
date: 2017-10-30
tags:
- 
- testtag

categories:
- home

---
```
vscode-front-matter generates a list of tags with a null entry in settings.json:
```json
{
    "frontMatter.taxonomy.tags": [
        "nodered",
        null,
        "testtag"
    ],
    "frontMatter.taxonomy.categories": [
        "home"
    ]
}
```
Null tags should not be included "Front Matter: Export all tags & categories to your settings" or should be ignored if included in settings.json.
