### ISSUE TITLE
Feedback: Enum/Select in schema fields

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#859]
I am adding this as feedback, because I don't know if it is maybe integrated or I am overlooking something...

Let's assume I have a data file with a blogroll, and in that blogroll I want to add a field that demarks what type of link that item is: how do I implement some form of enum or select for that field? For instance `["person", "website", "feed"]` or something along the lines and in frontmatter it shows either three radio boxed items in a line that I can select one, or a select field with three items (and their labels)? 

In JSON schema we have enum:

```yaml
properties:
  type:
    type: string
    enum:
      - blog
      - video
      - music
      - page
      - documentation
```

But it doesn't seem that this is integrated. At least the docs are not talking about it and trying some forms of settings on JSON-"schema" values won't work.
